const NOT_FOUND_ERROR_CODE = 404;
const INCORRECT_DATA_ERROR_CODE = 400;
const DEFAULT_ERROR_CODE = 500;
const STATUS_OK = 200;
const STATUS_CREATED = 201;

module.exports = {
  NOT_FOUND_ERROR_CODE, INCORRECT_DATA_ERROR_CODE, DEFAULT_ERROR_CODE, STATUS_OK, STATUS_CREATED,
};
