const NOT_FOUND_ERROR_CODE = 404;
const INCORRECT_DATA_ERROR_CODE = 400;
const DEFAULT_ERROR_CODE = 500;
const STATUS_CREATED = 201;
const SALT_NUMBER = 10;
const SECRET_KEY = 'YandexPraktikum';
const EXPIRES_IN_VALUE = '7d';

module.exports = {
  NOT_FOUND_ERROR_CODE,
  INCORRECT_DATA_ERROR_CODE,
  DEFAULT_ERROR_CODE,
  STATUS_CREATED,
  SALT_NUMBER,
  SECRET_KEY,
  EXPIRES_IN_VALUE,
};
